# Generated by Django 4.2.2 on 2023-06-20 06:26

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_course_rename_widgets_widget_delete_courses_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='publised_at',
        ),
        migrations.AlterField(
            model_name='article',
            name='keywords',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200, null=True), size=None), size=None),
        ),
    ]
