# Generated by Django 4.2.2 on 2023-06-20 06:37

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_alter_article_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='keywords',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200, null=True), blank=True, default=[], size=10),
        ),
        migrations.AlterField(
            model_name='course',
            name='doc_acceptance',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.DateField(blank=True, null=True), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='course',
            name='programs',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='course',
            name='required_docs',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='news',
            name='keywords',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None),
        ),
    ]
