# Generated by Django 4.2.2 on 2023-06-20 06:37

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_alter_article_keywords_alter_course_doc_acceptance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='keywords',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200, null=True), blank=True, default=list, size=10),
        ),
    ]
