# Generated by Django 4.2.2 on 2023-06-22 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0015_alter_article_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='widget',
            name='file_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='widget',
            name='link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
