# Generated by Django 4.2.2 on 2023-06-22 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0016_widget_file_link_widget_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='publised_at',
            new_name='news_date',
        ),
    ]
